package com.leetcode.learning.q1003;

import java.util.*;

public class Solution {

    private final static String TARGET = "abc";

    private Stack<Character> stack = new Stack();

    public boolean isValid(String S) {
        int originLength = S.length();

        if(S.length() < TARGET.length() || originLength % TARGET.length() !=0 ) {
            return false;
        }

        int distA = originLength - S.replaceAll("a", "").length();
        int distB = originLength - S.replaceAll("b", "").length();
        int distC = originLength - S.replaceAll("c", "").length();
        if (distA != distB || distB != distC) {
            return false;
        }

        for (int i = 0; i < S.length(); i++) {
            char c = S.charAt(i);
            if(TARGET.charAt(2) == c) {
                if (stack.size() < 2) {
                    return false;
                }

                if(stack.pop() != TARGET.charAt(1)) {
                    return false;
                }

                if(stack.pop() != TARGET.charAt(0)) {
                    return false;
                }
            } else {
                stack.push(c);
            }
        }

        return true;
    }



    public static void main(String[] args) {
        long start = System.currentTimeMillis();

        Solution solution = new Solution();
        System.out.println(solution.isValid("aabcbc"));
        System.out.println(solution.isValid("abcabcababcc"));
        System.out.println(solution.isValid("abccba"));
        System.out.println(solution.isValid("cababc"));
        System.out.println(solution.isValid("aabcbbccaaccabaacbabbaacaaabbaabbccbababcbaccacbabccaabacbbcbcaccccbcaaaccabbbbaacccbcabaaaaacbcbbccbacccbbcabaccacccaccbbababbcbcacacccabcacaccbaacabacbbcbcbaaaaaccabbaacacbabbcbaabbbacbccbcbcaaaacabaacababacbacaacbaabaccabcccabaccbbbbbbbbabcacabbcccaaaabacabcbbbbcbbabccaaaabbbaaabccbbccacbcabacbaabacacacabccbabcaccacccbbcbabcbabcaaccaabcabcccbaacaaaacbabbccaabbbacbbcbbcaabbbcbcbaabbccccbacabaacaaccbcababbaaaabcabacbaacbabcaaacbcccababbbccccbbcacacabaccccbaacccbacaaaaabacabbaccbcccbbbcaaabbcaacccbabacbababcaacacbaccaaaccaacabbcbbbaacaccccacacbcbbaabbabbbabaabaabbcccbccbcccbbccbacaabbacabbaccaccaccbcbccaccbbacbccbbaaaacbcbbbaacccbaaabccbbaabbabaabbbcbcaaccaaacbbcbbbaabcbacacbabcbbbccbabcaaaaaccbbbaaaabcbbbbaabcbbbacaabcaabcaabccaccababacbcbbbabcabcccccbacabbbabaaccacbcaacbccabbcccbacabbbccbbccaacabaccacccaacaabbbbcbcabbcbababbbccabbacacbabbccccbcccbcbbbbcacacbbaccabbcabcbacbaaabbbbbcacaaccbcabcacbcbaaaaacbccbacccbabccacaaccaaaaababbacacbaccacbacbacaaaabbaccbbcbbcabcaabcbcccaccabccbcbbaccaabcbccbccccaccaaccbabababbbabbbbbaacacaaccccaabbaabcbcabbbacabcaabacbbcbaacaaccbacbccbabbacabcbacacbbbbaacacaaabcaccbccaabcbabacbcabcacacacaccabbcbbaabbcabacaaccbaccacabbbbbabcaacaaabbaabaabbbababacbbaaacaccbbcbabcbcacacbaaabcbbabbaaabcbaacbbbbcacbcccbaccaabcaacbaabcabcaacbbbcbccbacaabbacabcabbcbbaacbcbcababaabbcbbaaacccabcaacacabbaabbbababcbbcaaaabccacbbbababcbccaaccacaccacaccbaabacbabbacabaaaababbbabcbccbccbaabbbcacbbcbbabcaacbbabaabaabaabaabbacabaccaccbbcbaccbbbcaaabcbcbcbcbbccbcaaaacabbbaabbcbabbcaacbaaccbbccbbaababcaacacaaacaabcacbbbccacbcaabbbaccbccabbbbbcaaaaccaccbcabbabbcbaababcaabccbcbccbccccbbbbbbcacccaabaaacabcbacacccbbbcbbcaccababbccacbcbaccacaabcccbbbcbcabbbcacbcabaccaacbccacbbabbbcacabbbabbabaaababcabcccaaccccbabcbbabbabcaaccccbacbbbcbcbaacabbbaaaacbcbbabcaaabacbccbcaaccabababcbbbabcbbcbabacaacbcbcaabbbbbaabccbacbaacbcbcaabcbababaabacbcbabbbccaabcabaccaabcacbcaacabbcbcacccbcbbcaccabcccaccacccabacabcbaacababaccbbbbcabbaabcbabacabacabcaccacabbacbbbacbacabcccaabaccbaaacabccaacaacaaababacaacbbbababcbabcaccaacbbcbaaaabcacbbaccbbcbcaabccabcbbabaaccabcbabcbbccacbcbbbbacbabcacaabbcabbaabbacccbaaaacbaaabbcccacaccbabbbcabcbbcbababcbbcabbacacababbbabcbbcbcbbccbccacbccbcabcbcbcbcaacabbbabbbbcaccbcabaabcaaabaaaabcaacbccbacbbcbcabbbbacabbaacbaaabaaabcbccbbacbaacbabbcbaacacbcbabbaacbcbacbacaabacbbbbbaaaacbacbccbccababbcbbacccccbcabbbbccacacacbabcbacccbcacbacbbbccbbbccabccbcaccbbccbabcaaacbcbbacccbcccababacaabbaaaabcccbacacabcbacaaaccaccccbacaaaacabbcccccaccacccaaaabcbbcbcaaaccbbbcbbbbcabbaaabccbcbcbbbcabbbbbacbcaccccacaacabcacabbbaabcabbcbcbacbbcbabaccbabbbaaabbcbbababcbbaaabbabbcbbbbccccaacccaabcccbbaaabbbbcccbaccabcabcbbaababccbbcabaccaaaacabbabcababcccccabbcbaaaabccaabccababbacbbbaccccacbaacaacbcaaabbacabcccabacaacaacccaacaccbbabacbccacabacbabcbbcbcbaabbaabbbacacabcbccccbcccccbbbacbbbbbbacccccbcacaccbccabcbabcaacbbbcabbbcaaaaaabbcccbcccabaaabcccabacbaacccbabacbcbbcbccacaacabcacccabcacacccaaccabaaabbaacaabbbbbaabbbbcccbaabaabcccbcbbbccccbcbbacbbbcababcabaacbacacabccccaacaaababbcacbccaaabcacabacbccaccbaabaccbbcbaaacbcabacaabcabcacbacaccbccbbbcbaccbbbacabaacbbbababcabbacccbbcbbcbabbcccabaaaaaacbcbcaaaacaaaacbbabbabbababacabbbcacaacbcabbcaccacabacabcbcacbaaccccaabacccababbabbacaabbcbcbcbcbbacbcababbaaababcbcaaaaccccbccabcacbabbababcbbbcbbbaaccccaccabbaccacbaaaaccbccbaabcacbaacccaccbbbcbaacbccaaccabcabaaabacbacbcabaacabcbccbcacccacaaaacbbbbbbbcbabacccccacccbccaccacabaabcacbabbbbacaabcababbbbcbaaaaacbabaaacbaaacaacacbbbaccbaaaccaabbcbccaacbccaababcaaaabcacabcacbacbabcacaacbaaccbbacccccabcbaacaccaabcabcbbabaccacaacaacccccabcbccccaaacbbcbbbbbaccabcacaaaacbccccaabaacbbcbccbcccabababbcabaabccccbbbabacaaaababcabcbabababbbcbaaabcababbacabcbbacabababbbccbabccbabaaaaaacccaacaacbccbabcaaabcbbcabaabaccbbaaabcbaabbabcbcaaacccccacccbaacabbaabccaaccbbacccabcabcabbbcbabacaabaaabcbaacccaccccabbbbacbaabababcaaacbcbbcacaaaaacacaaaaabaccbcacbacbbcbabcccacbccacbbccbcaacaaaaccabbaaaccccaacaacbabbcccbbbbacbaacbbbabbccbcbcacbcccabcccbabccacbbbcbbbaabcbaabcccbbababbaabbcbabbbbcbbabbacbbcaaacccaccccaaaacaaacaccbbbaccacaccbcaaabaacbaacacbbbbbccbbaacaabccaccccaaccbccabaabcacacbcaabbaababbbbcbbbbbcbcacacccabbacabcbbbbcbacaccbccbcaacccabaccabcaacbcabacaaaaacbcabbbabbbaaacaaaccacabbcbabcaabbbccbcbaacbacbccbcbccaababcabacbcabcaccaacbcabbccaaacaacbaaaaabccbacacccccaaacbbabbbbaacaacaaabcbcbacbbbbbcacbbbabaccccccbbbbacacaaacacbaacacaacbbcaaccbbbbbcababbbbccbaacbcbcaababcbaccabbcbababccbacccaccabbaccbaabbabbccaccbbcccbaaaabaabbacacbaaabacbcaabaaabbbacabbabaacaacbbcbcabcbccbbbcaccccccabbacbaaacccccbcbbbbacabacbcabbbabbbbabccccbaacabcbcaabcaababbbccccaaacabaccbaaccccccbbacbaaaaccbcbbcbbabbaabcaabbcbccaccccbaababcbaaacaaccacbabbacbbbcbcccabbcbaacaacbababaaccbcbbbbccbcbacacbbabcabcbcaabcbbbbacbabbccacbacbaabcbaaaabcaaaccacacbabaaacbbbaacbbccacbabacabcabbcacacaababbccabbabcaababbcbccaaaabbbbaccacbccbbccabbbabaabbcbcbaacaaacbabbcabbaccbccaaaabaaccbbbcababbbacbcccacbbcaaaabbbcbcacbcacbbabacbabaaacbcabccabbcaacacacbaabbccbaabcbbbababaabbcaaacbbcacbabbabaccabbcbaccbccbcacaccabbbaaccbaaacbaccbabaccabbccbbabbbacbbcccaccccaacaaccabbbacaaacaccccaacbabaccbbccbcabccbaaaaccababcaabcbaccbcbcbaaaaabcabbcbcccaaababaccbbabaaccbbaababccbbcbcaccaaaabbbbbbababbcbaccacbcbababbcbbcbbbbabacabcbbbcccacbaabbbbcbaabcbcbcacaabcbbbbccbbccbbabbbbbccacaaabbcbbbbaabccabbcccaabbabbacaacbccbbbccccababcabacbccccabbcabccbbcbaccbcaabcaaaabccaacbcaccaabaacbbcbcaccccaccaccacbccacccbbbbaacbbbbcabbccccccacacbcbccbcccaccaacbcaabcaabbbbaacbbbbacbaabbbabbccbcbbcacaccccccbcbbbcaabcacbacaaabaaaabcaaccccabbcaaaaacbaabacbccccbbbacababcbaaaabccccabcaabcbacaaaababcaacabbbbbccaaabbacaaabaabcbabbaaccbaacbabccbcacbbaabbacabaabcbbaacbbcabccaccaaaaaaccacabbbcbcaaacaababbabbccbbacaabacbcccacbacbcbaabbcaaaacccaccabcbbbcccacbcccacbbcccabcabcaccaccaaccaabbaaababbccccbccbcbbbccbbaaaccabbabbcbaaaabcbbccbcbbabccabaacccccacbcbccbccccacaaabacaaaababcbbccaabbbababcbcbccccabbbbbabccaccaccbcbcabaccabcbcbcccbacbbcaccabccbcccacaaccabcbcbbaaaabccaacaabacbccbcbacbbcbaaabaabbcbbacbaccbacaccaccbbccbbacbcbbaaababcaacaaaababbacbbbbcaabcabbbbccaacbaaccbacaaccbbbcccabbcbccaccabcaacacbbbccbacbcbccbccbaabbaacaaacabccbacccccbcaaaaababbbcbabcabbbacacaabcababcccacabbaabbbcbaaabcabcbbbaaabacbbbcbabbcaabbcccbcacabaabccbacbbabbcaaacbcabaabcaacbcbbcabcbbbcacccbbbabaacbbabcabbcaccacaabababcabcbbcbaaacccacacbcaaaacccacacabbbbacbaabacbbcbabaaaabbabcbaaaaabcaaccbbcbbbbcbbabcbacaccaaaaabccabcabacccbabaabccbaacccccbabcabcacccccaacbbccbcacbbccaababcbcccaabcbbccccacacacabccbcaacacbcbbbbccaabcbacccacbcababbcbccacbaabaacaabacbcacbccbbbcacbcbcbabcbaacaccbaacbccccbaccabbaabccabcbaaabacbbaaaabbcbbbbacaaccaacaababcbccaaaaaaaaaaaaacccbcbccccbbcccbbabcbbaacbacacaabaaaaccbcbcbbcbccabbbcbccccabbabbbacccacccbaabbaaacbbbbabccbaacaaaacacbbaacbcbccaaabaccbbbabbbabcbcaaaacaaaaccbcabbab"));
        System.out.println(solution.isValid("cbbbbcaaaccbaabccabacabcacbabbabbcbacabacabcabbccbccbccbcaccbacaabaaababacbbccabbcbcbabbcbabcacabcbababcaccbcbbbaaabbcbccaaabcbababaaaccbacbbcaabbacbbbabcccacbaacacccbcccbbbbccaaabaaababcbbaacbcccaaabcbacccaacbbbaabababbbbababcbaaaabbcacbacaaabbcacbccbbbbaabcacbccababaaaacbabbbaaccbccaacacccaaabacaaaacacbbaabcabcbcccbcabaaaccbcbaaaccaacbabcaabbccacbbcbbbcaccbaccacaabcbcccacacaccaabbcaaababbbbbbcabcbbacabbbbbaabcbabbbccaabccabccaaaccabcbcbabbcaccabcbaabaaabacccacacabbaccbabbbacaaabacacabacbcabaabaccacbbaacbcaccaccbacbaacbcbabccbcacbbbcabaabaabbabbcbbbcbbaabababcacacacbcabbccbbbacacccbbbbbbcbabaacacbbbaccbcaaccaccabbabbcbaababbcacaababaababcccbbcaaaabccabbbcbbaacacabaabbaabcaabaacaabcbaaabaccbbcbaaababcacaacabcbbbbabaccbabbccacbbbcbacccbbbcabaaaacacaacbbcabbbbaacacababccaaacaccaaaacbabbcacaabaacaaabcacaabcaaaaaaacbbabbababcbbccbabbabaccbbcccacaabcbccacaacbacbcccbabababababbacbabacbcccccbbcbcbabbbbaacbbabacccbcccbcaccabacaacbbbabacccccbcbbbacaccacccbccbbbcbcbaacbbaabaacbacabacacaaaccaaacabbbaabcaacacbaaabcbbbbcaacaaccbbbccbababcbcacbcbcbbaabcacbbcacaacacccababbcacbbcaaccaacbbabccabbccbacacaccccccbcbbcbabcabbcaabbaabaccababcbcbcbabbcabcbabacaababcbcacbaacbcccbbbcbaacabcccbbabccacaaaaccaabccbbaabababcacabbaccbbacbcbcaacabbaccccabbccbbcabcbcccaabcccbabbacabccaacababcaaaacccbabcccabcccabccbacaacabcbbaacbaacbbcbaaaacbbcaccbacaccaaaccabaaabcbabababbcbbcbacbabaacbbbaacabbbaacbaccccaaccccabcabaabaccacaaacabbbbcbccccbcacaacbcbbbcbabcbccaaabbaccbaacccbaacbbbbcccacbcacabccbbcbabbccabbbaabaacbbacacacccbcbcbaabcccacbccbbcacaababbcbaaabaccaaaaacbbbacaaaaabbacaabacbcaccaacbacbaaaabcbaaabcccccbcacbccacbccccaacaaccbbcbabcbaacbbabbbbaabcacbaaacbbcabcbcbbbcabbbbcbcbacccbcaacaccccbcccacbbbbbacbccaabcbabcacacbbaccbbbaccbcaacacabaaccbccabbccbacbaacbbbbacacccabbbbabaaaabcbabcccacccababbabcabbbaabacbcbaaccccacbbbccccacaaaacabaacaccaabccacbbbccaabbccccbccbbbabacbabacbabcbaccbabbaccaccbabcababbbbcbbcabababaacaccacbacccabcacbbbcccacacabcabccaacbacbcaccbaaaacbbccccccaabbabcbaaaacbbbaabbcacabaccabbcbbbbabbccabcccccbbcbbcccbbacacbaaacccccbbcaacaacabbbcacaaaaaacabacbbbbbacbbacbbcbbbcbbaccaacbcbaaaabbbababbbccccaabacbcaacacbbcacccaacccccbbccbbbbbacbabcabbcacccbcbabbaabbacaabaacabcccbbbbcacabbbaacaaacbabbaccaacabbcbbaaabaccaccacccbbbacaccacbabbaacabbcbbcbbccbbbacbbacbbbabcaababaacbaacaabbacbabbccccaccccaabbaaabcccabccbccaaacbbccabbbcbaaaacabbbbbbcbbacbbcccbbabbacbbccbccccccaabacaabaaaccccaabcacbbccbbabccaacccaababbccbabcbabcccbbabaaaababaabbbcbabbccaacbacccaabccababccabcbbcccaacabbbcbaaabbcaacbbbaabaacbbacbbcacbcabccbbccbcbcbbcbaacacbbbbcacbabbaacccaccbacbbcabbbbabcabaabbcaacabbbbbbccbacacaaacabaacbcbacbaaacabcbbcbbbabaccabaaaacaaaaaacaccbccaabaabcaaabaaababcabcccbbcacbcacaabbaaacbbbbcbabaabaabacacaaccbaacabcacbaaabbacccbccaabbaccabbbbacbcbccbcbbcbcbcbcabcccbccaacacccccbbbabbabcbcbabbacaabcbaabbacbcaccacacccacbabbabacababcbaccaabcbacabbacaaaabccbbbbcaabbccbcccccbccacaababcccacbcbcbccabbcbcbcccccccacaaccbbccccbbbcabbacaacacbbabcaacacbcccacbcbcbaaaaccaabaaabcabcaacaacabaacccabaabbaac"));
        long stop = System.currentTimeMillis();
        System.out.println(stop - start);
    }
}
